---
# tasks file for tomrole
- name: install tomcat7
  apt:
   name: tomcat7
   state: present

- name: copy config file into tomcat7
  template:
    src: templates/config.j2
    dest: /etc/default/tomcat7
  notify: restarttomcat

- name: download packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - tomcat7-docs 
    - tomcat7-admin
    - tomcat7-examples

- name: copy tomuser.xml file into tomcat7
  template:
    src: templates/user.j2
    dest: /etc/tomcat7/tomcat-users.xml 
  notify: restarttomcat

- name: deploy java application
    url: 
    dest: /var/lib/tomcat7/webapps/mahaLogin.war
    force_basic_auth: yes
  notify: restarttomcat
